spring:
  application:
    name: pigeon-web
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pigeon?serverTimezone=Asia/Shanghai&characterEncoding=utf8
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    time-zone: UTC
server:
  port: 9797
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰形式显示
    map-underscore-to-camel-case: true
  #扫描mapper.xml文件
  mapper-locations: classpath:mappers/*.xml